### ISSUE TITLE
Добавить страницу с моделированием электростатического поля

### ISSUE THREAD

**Issue by khusamov** [Vasilii-Khusamov/Site#2]
![image](https://github.com/Vasilii-Khusamov/Site/assets/4146998/55e50dd9-c622-4b40-a3f5-9160f92f9b60)

Требуется использовать тег <canvas> для рисования поля.

```html
<!doctype html>
<html>
	<head>
		<title>canvasExample</title>
        	<meta charset='utf-8' />
	</head>
	<body>
		<canvas height='320' width='480' id='example'>
			Ваш браузер не поддерживает тег canvas.
		</canvas>
		<script>
			var example = document.getElementById("example"),
			    ctx     = example.getContext('2d');
			ctx.fillRect(0, 0, example.width, example.height);
		</script>
	</body>
</html>
```

Методы ctx для рисования линии:

```javascript
ctx.moveTo(x, y) // перемещает "курсор" в позицию x, y и делает её текущей
ctx.lineTo(x, y) // ведёт линию из текущей позиции в указанную, и делает в последствии указанную текущей
ctx.stroke()
```

Описание класса объекта, который возвращает метод `example.getContext('2d')`:  
https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D

Сейчас сделать:
- [x] Тестирующая функция на createArrowVertexes()
- [x] Вывести на экран сетку из точек (1 пиксель черный)
- [x] Вывести строку с масштабом "Масштаб 10 метров между точками"
- [x] Добавить массив с зарядами и сделать вывод зарядов в виде кружков
- [x] Сделать вывод напряженности в точках сетки
- [x] Сделать рефакторинг страницы
- [x] Исправить вычисления цвета стрелки

**Comment by khusamov** [comment]
```
<a href="./electrostatic-field-modeling.html">Имя ссылки</a>
```

**Comment by khusamov** [comment]
Сейчас сделать:
- [ ] Тестирующая функция на createArrowVertexes()
- [ ] Вывести на экран сетку из точек (1 пиксель черный)
- [ ] Вывести строку с масштабом "Масштаб 10 метров между точками"

**Comment by Vasilii-Khusamov** [comment]
Я нашёл способ рисования одного пикселя:
```javascript
ctx.fillRect(x,y,1,1); // fill in the pixel at x, y
```
